export const RouterPath = {
  ROOT: '/',
  HOME: '/',
  POST: '/post',
  EDIT: '/edit/:userPostId',
  LOGIN: '/login',
  JOIN: '/join',
  DETAIL: '/detail/:userPostId',
  MYPAGE: '/mypage',
  POLICY: '/policy',
  PRIVACY_POLICY: '/policy/privacy',
  TERMS_OF_SERVICE: '/policy/terms',
  LISTPAGE: '/list',
  LISTPAGE_CATEGORY: '/list/category/:category',
  LISTPAGE_SEARCH: '/list/search/:search',
}
