export const RouterPath = {
  ROOT: '/',
  HOME: '/',
  POST: '/post',
  LOGIN: '/login',
  JOIN: '/join',
  DETAIL: '/detail',
  MYPAGE: '/mypage',
  POLICY: '/policy',
  PRIVACY_POLICY:'/policy/privacy',
  TERMS_OF_SERVICE: '/policy/terms',
  LISTPAGE: '/list',
  LISTPAGE_CATEGORY: '/list/category',
  LISTPAGE_SEARCH: '/list/search',
}
